version: "3.8"

services:

  ##### MongoDB #####
  mongodb:
    container_name: mongodb
    image: mongo:6.0.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=eventsshop
    volumes:
      - ./demo_data/listings.json:/data/listings.json
      - ./demo_data/populate.sh:/docker-entrypoint-initdb.d/populate.sh
      - ./tmp/mongo/data/db:/data/db
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8087:8081"
    restart: unless-stopped
    depends_on:
      - mongodb

  ##### Seq #####
  seq:
    container_name: "seq_service"
    image: datalust/seq:2022.1
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./tmp/seq/data:/data
    ports:
      - "8191:80"
      - "5341:5341"
networks:
  default:
    name: checkoutevents
    driver: bridge
