version: "3.8"

services:
  ##### StripeEvents Checkout App #####
  webapp:
    build:
      context: ./src/
      dockerfile: Dockerfile.WebHost
    container_name: checkoutevents_server
    env_file:
      - src/StripeEventsCheckout.WebHost/.env
      - .env
    ports:
      - "5276:5276"
networks:
  default:
    name: checkoutevents
    external: true
