version: "3.8"

services:

  ##### MongoDB #####
  mongodb:
    container_name: mongodb
    image: mongo:5.0.7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=eventsshop
    volumes:
      - ./demo_data/listings.json:/data/listings.json
      - ./demo_data/populate.sh:/docker-entrypoint-initdb.d/populate.sh
      - ./tmp/mongo/data/db:/data/db
    ports:
      - "27017:27017"

  ##### Rabbitmq #####
  rabbitmq:
    image: "rabbitmq:3.10.5-management"
    container_name: "rabbitmq_server"
    hostname: "rabbitmq_server"
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
      - RABBITMQ_ERLANG_COOKIE=demo_cookie_1234
    volumes:
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "5672:5672"
      - "15672:15672"

  ##### Redis #####
  redis:    
    image: "redis:7.0.2-alpine"
    container_name: "redis_service"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
 
  ##### Zipkin #####
  zipkin:
    container_name: "zipkin_service"
    image: "openzipkin/zipkin:2.23.16"
    ports:
      - "9411:9411"
  
  ##### otel collector #####
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    container_name: "collector_service"
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:   
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension

  ##### Seq #####
  seq:
    container_name: "seq_service"
    image: datalust/seq:2022.1
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./tmp/seq/data:/data
    ports:
      - "8191:80"

networks:
  default:
    name: checkoutevents
    driver: bridge
