version: "3.8"

services:

  ##### MongoDB #####
  mongodb:
    container_name: mongodb
    image: mongo:5.0.7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=eventsshop
    volumes:
      - ./demo_data/listings.json:/data/listings.json
      - ./demo_data/populate.sh:/docker-entrypoint-initdb.d/populate.sh
      - ./tmp/mongo/data/db:/data/db
    ports:
      - "27017:27017"

  ##### Rabbitmq #####
  rabbitmq:
    image: "rabbitmq:3.10.5-management"
    container_name: "rabbitmq_server"
    hostname: "rabbitmq_server"
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
      - RABBITMQ_ERLANG_COOKIE=demo_cookie_1234
    volumes:
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "5672:5672"
      - "15672:15672"

  ##### Zipkin #####
  zipkin:
    container_name: "zipkin_service"
    image: "openzipkin/zipkin:2.23.16"
    ports:
      - 9411:9411

  ##### Seq #####
  seq:
    container_name: "seq_service"
    image: datalust/seq:2022.1
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./tmp/seq/data:/data
    ports:
      - "8191:80"

  ##### Seq Gelf ##### 
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
networks:
  default:
    name: checkoutevents
    driver: bridge
