version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stripe-events"
s3_bucket = "sam-template-store"
s3_prefix = "stripe-events"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
