apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmqbus
  namespace: default
spec:
  type: pubsub.rabbitmq
  metadata:
    - name: host
      value: "amqp://demo:demo@rabbitmq_server:5672/"
    - name: durable
      value: "false"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"