apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redisbus
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis_service:6379
    - name: redisPassword
      secretKeyRef:
        name: redispass
        key: redispass
    - name: enableTLS
      value: "false"
auth:
  secretStore: localsecrets